import os
import smtplib
import pandas as pd
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from dotenv import load_dotenv, set_key

ENV_FILE = ".env"

def init_env():
    if not os.path.exists(ENV_FILE):
        with open(ENV_FILE, "w") as f:
            f.write("SENDER_EMAIL=admin@college.edu\n")
            f.write("SENDER_PASSWORD=app_password_here\n")
            f.write("HOD_EMAIL=hod@college.edu\n")
            f.write("COLLEGE_NAME=Smart Classroom Academic Platform\n")
            f.write("SMTP_SERVER=smtp.gmail.com\n")
            f.write("SMTP_PORT=587\n")

init_env()
load_dotenv(ENV_FILE, override=True)

def get_email_config():
    load_dotenv(ENV_FILE, override=True)
    return {
        "SENDER_EMAIL": os.getenv("SENDER_EMAIL", ""),
        "SENDER_PASSWORD": os.getenv("SENDER_PASSWORD", ""),
        "HOD_EMAIL": os.getenv("HOD_EMAIL", ""),
        "COLLEGE_NAME": os.getenv("COLLEGE_NAME", "Smart Classroom Platform"),
        "SMTP_SERVER": os.getenv("SMTP_SERVER", "smtp.gmail.com"),
        "SMTP_PORT": int(os.getenv("SMTP_PORT", 587))
    }

def update_email_config(sender_email, sender_password, hod_email):
    set_key(ENV_FILE, "SENDER_EMAIL", sender_email)
    set_key(ENV_FILE, "SENDER_PASSWORD", sender_password)
    set_key(ENV_FILE, "HOD_EMAIL", hod_email)
    load_dotenv(ENV_FILE, override=True)

def _send_email_smtp(to_email, subject, html_body, attachment_path=None):
    config = get_email_config()
    sender = config["SENDER_EMAIL"]
    password = config["SENDER_PASSWORD"]
    server_host = config["SMTP_SERVER"]
    port = config["SMTP_PORT"]

    if not sender or not password or "app_password" in password:
        return False, "Email config missing! Please set your Gmail & App Password in Settings."

    try:
        msg = MIMEMultipart('alternative')
        msg['From'] = f"{config['COLLEGE_NAME']} <{sender}>"
        msg['To'] = to_email
        msg['Subject'] = subject

        msg.attach(MIMEText(html_body, 'html'))

        if attachment_path and os.path.exists(attachment_path):
            with open(attachment_path, "rb") as f:
                attach = MIMEApplication(f.read(), _subtype="pdf")
                attach.add_header('Content-Disposition', 'attachment', filename=os.path.basename(attachment_path))
                msg.attach(attach)

        server = smtplib.SMTP(server_host, port)
        server.starttls()
        server.login(sender, password)
        server.sendmail(sender, [to_email], msg.as_string())
        server.quit()
        return True, "Email sent successfully!"
    except Exception as e:
        return False, f"SMTP Error: {str(e)}"


def send_defaulter_alert_email(student_id, student_name, parent_email, att_pct, total_sessions, attended_sessions):
    """Send HTML warning email to student & parent for <75% attendance."""
    config = get_email_config()
    target_email = parent_email if (parent_email and "@" in str(parent_email)) else config["SENDER_EMAIL"]

    subject = f"⚠️ URGENT: Low Attendance Warning — {student_name} ({student_id})"

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; padding: 25px; border: 1px solid #e0e0e0;">
            <h2 style="color: #d32f2f; margin-top: 0;">⚠️ Low Attendance Warning Notice</h2>
            <p>Dear Parent / Student,</p>
            <p>This is an automated notification from <b>{config['COLLEGE_NAME']}</b> regarding the academic attendance status for student <b>{student_name} (USN: {student_id})</b>.</p>

            <div style="background-color: #ffebee; border-left: 4px solid #d32f2f; padding: 15px; margin: 20px 0;">
                <h4 style="margin: 0 0 8px 0; color: #b71c1c;">Attendance Details:</h4>
                <p style="margin: 4px 0;"><b>Current Attendance:</b> <span style="color: #d32f2f; font-size: 18px; font-weight: bold;">{att_pct:.1f}%</span></p>
                <p style="margin: 4px 0;"><b>Sessions Attended:</b> {attended_sessions} / {total_sessions} Class Sessions</p>
                <p style="margin: 4px 0;"><b>Required Minimum Threshold:</b> 75.0%</p>
            </div>

            <p style="color: #555;">Please note that maintaining an attendance percentage below 75% may disqualify the student from attending upcoming semester examinations as per University guidelines.</p>
            <p>We urge you to meet the class coordinator or Head of Department (HOD) at the earliest to discuss this matter.</p>

            <hr style="border: 0; border-top: 1px solid #eee; margin: 25px 0;">
            <p style="font-size: 12px; color: #888;">This is an automated message generated by the Smart Classroom Face Recognition Platform. Please do not reply directly to this email.</p>
        </div>
    </body>
    </html>
    """

    return _send_email_smtp(target_email, subject, html_content)


def send_hod_summary_email(pdf_filepath, subject_name="All Subjects"):
    """Send monthly attendance PDF summary directly to the HOD."""
    config = get_email_config()
    hod_email = config["HOD_EMAIL"]

    if not hod_email or "@" in hod_email is False:
        return False, "HOD Email is not configured in Settings!"

    subject = f"🎓 Academic Attendance Summary Report — {subject_name}"
    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; padding: 20px;">
        <div style="max-width: 600px; background: white; padding: 20px; border-radius: 8px; border: 1px solid #ccc;">
            <h2 style="color: #003366;">Academic Attendance Summary Report</h2>
            <p>Respected HOD,</p>
            <p>Please find attached the official PDF attendance report for <b>{subject_name}</b> generated from the Smart Classroom Platform.</p>
            <p>The report includes complete session breakdowns, overall attendance percentages, and defaulter warnings (<75%).</p>
            <br/>
            <p>Best regards,<br/><b>Smart Classroom Platform Administrator</b></p>
        </div>
    </body>
    </html>
    """

    return _send_email_smtp(hod_email, subject, html_content, attachment_path=pdf_filepath)
